<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else if (elem.classList.contains('float')) {
        key = keyFloat;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++)
        filterItems[i].hidden = false;
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyFloat(colIndex) {
    return function(elem) {
        return Number(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>synapse.report.parallel.html</h1>
    <p>Report generated on 23-Mar-2022 at 19:07:15 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.1.1</p>
    <h2>Summary</h2>
    <p>34 tests ran in 127.27 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">34 passed</span>, <input checked="true" class="filter" data-test-result="skipped" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">2 skipped</span>, <input checked="true" class="filter" data-test-result="failed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">0 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable float" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="skipped results-table-row">
        <tr>
          <td class="col-result">Skipped</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_data_flow</td>
          <td class="col-duration">0.00</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">(&#x27;c:\\code\\azure-cli\\src\\azure-cli\\azure\\cli\\command_modules\\synapse\\tests\\latest\\test_synapse_scenario.py&#x27;, 2524, &#x27;Skipped: (InvalidTokenIssuer) Token Authentication failed with SecurityTokenInvalidIssuerException&#x27;)<br/></div></td></tr></tbody>
      <tbody class="skipped results-table-row">
        <tr>
          <td class="col-result">Skipped</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_workspace_with_cmk</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">(&#x27;c:\\code\\azure-cli\\src\\azure-cli\\azure\\cli\\command_modules\\synapse\\tests\\latest\\test_synapse_scenario.py&#x27;, 1221, &#x27;Skipped: (keyvaultfailure) KeyVault set-policy failed with Bad Request&#x27;)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_access_control</td>
          <td class="col-duration">0.95</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (RoleAssignmentNotFound) RoleAssignmentNotFound
Code: RoleAssignmentNotFound
Message: RoleAssignmentNotFound
ERROR    az_command_data_logger:azlogging.py:213 (RoleAssignmentNotFound) RoleAssignmentNotFound
Code: RoleAssignmentNotFound
Message: RoleAssignmentNotFound<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_dataset</td>
          <td class="col-duration">1.13</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (DatasetNotFound) The Dataset dataset was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: DatasetNotFound
Message: The Dataset dataset was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
ERROR    az_command_data_logger:azlogging.py:213 (DatasetNotFound) The Dataset dataset was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: DatasetNotFound
Message: The Dataset dataset was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_integration_runtime</td>
          <td class="col-duration">2.84</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  msrest.serialization:serialization.py:187 Readonly attribute type will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IntegrationRuntimeResource&#x27;&gt;
WARNING  msrest.serialization:serialization.py:187 Readonly attribute type will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IntegrationRuntimeResource&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 Operation returned an invalid status &#x27;Not Found&#x27;
ERROR    az_command_data_logger:azlogging.py:213 Operation returned an invalid status &#x27;Not Found&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_ip_firewall_rules</td>
          <td class="col-duration">1.74</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (IpFirewallRuleNotFound) clitest000004/rule000003
Code: IpFirewallRuleNotFound
Message: clitest000004/rule000003
ERROR    az_command_data_logger:azlogging.py:213 (IpFirewallRuleNotFound) clitest000004/rule000003
Code: IpFirewallRuleNotFound
Message: clitest000004/rule000003<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_attached_database_configuration</td>
          <td class="col-duration">9.00</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto attached-database-configuration&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000004/AttachedDatabaseConfigurations/conf000006&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000004/AttachedDatabaseConfigurations/conf000006&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000004/AttachedDatabaseConfigurations/conf000006&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000004/AttachedDatabaseConfigurations/conf000006&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_data_connection_event_grid</td>
          <td class="col-duration">6.62</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_data_connection_event_hub</td>
          <td class="col-duration">5.89</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000008/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_data_connection_iot_hub</td>
          <td class="col-duration">5.86</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto data-connection&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  azure.mgmt.core.policies._base:_base.py:99 Resource provider &#x27;Microsoft.Synapse&#x27; used by this operation is not registered. We are registering for you.
WARNING  azure.mgmt.core.policies._base:_base.py:118 Registration succeeded.
WARNING  msrest.serialization:serialization.py:185 container_uri is not a known attribute of class &lt;class &#x27;azure.mgmt.iothub.v2021_07_02.models._models_py3.StorageEndpointProperties&#x27;&gt; and will be ignored
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000007/kustoPools/testkstpool000003/Databases/testdtabase000004/DataConnections/dataConName000005&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_database</td>
          <td class="col-duration">5.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000005/kustoPools/testkstpool000003/Databases/testdtabase000004&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000005/kustoPools/testkstpool000003/Databases/testdtabase000004&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000005/kustoPools/testkstpool000003/Databases/testdtabase000004&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000005/kustoPools/testkstpool000003/Databases/testdtabase000004&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_database_principal_assignment</td>
          <td class="col-duration">5.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/Databases/testdtabase000004/PrincipalAssignments/kstprinpal000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/Databases/testdtabase000004/PrincipalAssignments/kstprinpal000005&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/Databases/testdtabase000004/PrincipalAssignments/kstprinpal000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/Databases/testdtabase000004/PrincipalAssignments/kstprinpal000005&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_pool</td>
          <td class="col-duration">10.26</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_pool_principal_assignment</td>
          <td class="col-duration">4.91</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto pool-principal-assignment&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/PrincipalAssignments/kstprinpal000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/PrincipalAssignments/kstprinpal000005&#x27; is not found.
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/PrincipalAssignments/kstprinpal000005&#x27; is not found.
Code: ResourceNotFound
Message: The resource with identifier &#x27;/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000006/kustoPools/testkstpool000003/PrincipalAssignments/kstprinpal000005&#x27; is not found.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_kusto_script</td>
          <td class="col-duration">8.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse kusto database&#x27; is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (KqlScriptNotFound) The KqlScript scriptname000005 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000007)
Code: KqlScriptNotFound
Message: The KqlScript scriptname000005 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000007)
ERROR    az_command_data_logger:azlogging.py:213 (KqlScriptNotFound) The KqlScript scriptname000005 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000007)
Code: KqlScriptNotFound
Message: The KqlScript scriptname000005 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000007)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_linked_service</td>
          <td class="col-duration">2.95</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (LinkedServiceNotFound) The LinkedService linkedservice was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: LinkedServiceNotFound
Message: The LinkedService linkedservice was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
ERROR    az_command_data_logger:azlogging.py:213 (LinkedServiceNotFound) The LinkedService linkedservice was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: LinkedServiceNotFound
Message: The LinkedService linkedservice was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_managed_private_endpoints</td>
          <td class="col-duration">4.42</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (UnknownError) {&quot;CorrelationId&quot;:&quot;&quot;,&quot;StatusCode&quot;:404,&quot;Message&quot;:&quot;Resource not found: Message=PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.&quot;,&quot;ExceptionDetail&quot;:&quot;Microsoft.Analytics.Clusters.Common.NetworkServiceException: PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.NetworkServiceImpl.GetPrivateEndpointAsync(String clientId, String referenceName, AbstractMetadataContext dbContext) in C:\\source\\Services\\NetworkService\\Service\\NetworkServiceImpl.cs:line 3295\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.GetPrivateEndpointAsync(String clientId, String referenceName) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\Controllers\\NetworkController.cs:line 278\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.ActivePartitionInstanceMiddleware.InvokeAsync(HttpContext context) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\ActivePartitionInstanceMiddleware.cs:line 90\r\n   at Microsoft.Analytics.Clusters.Common.Web.ServiceFabricResourceNotFoundMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ServiceFabricResourceNotFoundMiddleware.cs:line 50\r\n   at Microsoft.Analytics.Clusters.Common.Web.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ExceptionMiddleware.cs:line 54&quot;,&quot;ErrorType&quot;:&quot;PrivateEndpointNotFound&quot;,&quot;ErrorNumber&quot;:2145,&quot;ErrorOn&quot;:&quot;2021-12-09T03:45:05.8952402+00:00&quot;}
Code: UnknownError
Message: {&quot;CorrelationId&quot;:&quot;&quot;,&quot;StatusCode&quot;:404,&quot;Message&quot;:&quot;Resource not found: Message=PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.&quot;,&quot;ExceptionDetail&quot;:&quot;Microsoft.Analytics.Clusters.Common.NetworkServiceException: PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.NetworkServiceImpl.GetPrivateEndpointAsync(String clientId, String referenceName, AbstractMetadataContext dbContext) in C:\\source\\Services\\NetworkService\\Service\\NetworkServiceImpl.cs:line 3295\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.GetPrivateEndpointAsync(String clientId, String referenceName) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\Controllers\\NetworkController.cs:line 278\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.ActivePartitionInstanceMiddleware.InvokeAsync(HttpContext context) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\ActivePartitionInstanceMiddleware.cs:line 90\r\n   at Microsoft.Analytics.Clusters.Common.Web.ServiceFabricResourceNotFoundMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ServiceFabricResourceNotFoundMiddleware.cs:line 50\r\n   at Microsoft.Analytics.Clusters.Common.Web.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ExceptionMiddleware.cs:line 54&quot;,&quot;ErrorType&quot;:&quot;PrivateEndpointNotFound&quot;,&quot;ErrorNumber&quot;:2145,&quot;ErrorOn&quot;:&quot;2021-12-09T03:45:05.8952402+00:00&quot;}
ERROR    az_command_data_logger:azlogging.py:213 (UnknownError) {&quot;CorrelationId&quot;:&quot;&quot;,&quot;StatusCode&quot;:404,&quot;Message&quot;:&quot;Resource not found: Message=PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.&quot;,&quot;ExceptionDetail&quot;:&quot;Microsoft.Analytics.Clusters.Common.NetworkServiceException: PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.NetworkServiceImpl.GetPrivateEndpointAsync(String clientId, String referenceName, AbstractMetadataContext dbContext) in C:\\source\\Services\\NetworkService\\Service\\NetworkServiceImpl.cs:line 3295\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.GetPrivateEndpointAsync(String clientId, String referenceName) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\Controllers\\NetworkController.cs:line 278\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.ActivePartitionInstanceMiddleware.InvokeAsync(HttpContext context) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\ActivePartitionInstanceMiddleware.cs:line 90\r\n   at Microsoft.Analytics.Clusters.Common.Web.ServiceFabricResourceNotFoundMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ServiceFabricResourceNotFoundMiddleware.cs:line 50\r\n   at Microsoft.Analytics.Clusters.Common.Web.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ExceptionMiddleware.cs:line 54&quot;,&quot;ErrorType&quot;:&quot;PrivateEndpointNotFound&quot;,&quot;ErrorNumber&quot;:2145,&quot;ErrorOn&quot;:&quot;2021-12-09T03:45:05.8952402+00:00&quot;}
Code: UnknownError
Message: {&quot;CorrelationId&quot;:&quot;&quot;,&quot;StatusCode&quot;:404,&quot;Message&quot;:&quot;Resource not found: Message=PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.&quot;,&quot;ExceptionDetail&quot;:&quot;Microsoft.Analytics.Clusters.Common.NetworkServiceException: PrivateEndpoint has been deleted: ClientId=2b635e30-b991-4ab1-8bef-5af244ce4bba, ReferenceName=AzureDataLakeStoragePE, Cluster: 2b635e30-b991-4ab1-8bef-5af244ce4bba.\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.NetworkServiceImpl.GetPrivateEndpointAsync(String clientId, String referenceName, AbstractMetadataContext dbContext) in C:\\source\\Services\\NetworkService\\Service\\NetworkServiceImpl.cs:line 3295\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.GetPrivateEndpointAsync(String clientId, String referenceName) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\Controllers\\NetworkController.cs:line 278\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.ActivePartitionInstanceMiddleware.InvokeAsync(HttpContext context) in C:\\source\\Services\\NetworkService\\NetworkServiceBE\\ActivePartitionInstanceMiddleware.cs:line 90\r\n   at Microsoft.Analytics.Clusters.Common.Web.ServiceFabricResourceNotFoundMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ServiceFabricResourceNotFoundMiddleware.cs:line 50\r\n   at Microsoft.Analytics.Clusters.Common.Web.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\Shared\\Web\\ExceptionMiddleware.cs:line 54&quot;,&quot;ErrorType&quot;:&quot;PrivateEndpointNotFound&quot;,&quot;ErrorNumber&quot;:2145,&quot;ErrorOn&quot;:&quot;2021-12-09T03:45:05.8952402+00:00&quot;}<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_managed_virtual_network_workspace</td>
          <td class="col-duration">1.80</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_notebook</td>
          <td class="col-duration">3.77</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>{&#x27;entityState&#x27;: None, &#x27;renameOperationDetails&#x27;: None, &#x27;big_data_pool&#x27;: {&#x27;type&#x27;: &#x27;BigDataPoolReference&#x27;, &#x27;reference_name&#x27;: &#x27;testpool&#x27;}, &#x27;session_properties&#x27;: {&#x27;driver_memory&#x27;: &#x27;28g&#x27;, &#x27;driver_cores&#x27;: 4, &#x27;executor_memory&#x27;: &#x27;28g&#x27;, &#x27;executor_cores&#x27;: 4, &#x27;num_executors&#x27;: 2}, &#x27;metadata&#x27;: {&#x27;a365ComputeOptions&#x27;: None, &#x27;sessionKeepAliveTimeout&#x27;: 0, &#x27;language_info&#x27;: {&#x27;name&#x27;: &#x27;python&#x27;}}, &#x27;nbformat&#x27;: 4, &#x27;nbformat_minor&#x27;: 2, &#x27;cells&#x27;: [{&#x27;execution_count&#x27;: None, &#x27;cell_type&#x27;: &#x27;code&#x27;, &#x27;metadata&#x27;: {}, &#x27;source&#x27;: [&#x27;print(&quot;hello from portal&quot;)&#x27;], &#x27;outputs&#x27;: []}], &#x27;folder&#x27;: {&#x27;name&#x27;: &#x27;testfolder/testsubfolder&#x27;}}
<br/> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
WARNING  msrest.serialization:serialization.py:185 spark_log_folder is not a known attribute of class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.BigDataPoolResourceInfo&#x27;&gt; and will be ignored
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 Operation returned an invalid status &#x27;Not Found&#x27;
ERROR    az_command_data_logger:azlogging.py:213 Operation returned an invalid status &#x27;Not Found&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_pipeline</td>
          <td class="col-duration">2.54</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (PipelineNotFound) The Pipeline pipeline was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
Code: PipelineNotFound
Message: The Pipeline pipeline was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
ERROR    az_command_data_logger:azlogging.py:213 (PipelineNotFound) The Pipeline pipeline was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
Code: PipelineNotFound
Message: The Pipeline pipeline was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_spark_job</td>
          <td class="col-duration">0.99</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_spark_job_definition</td>
          <td class="col-duration">3.34</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
WARNING  msrest.serialization:serialization.py:185 spark_log_folder is not a known attribute of class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.BigDataPoolResourceInfo&#x27;&gt; and will be ignored
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (SparkJobDefinitionNotFound) The SparkJobDefinition SparkAutoCreate1 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: SparkJobDefinitionNotFound
Message: The SparkJobDefinition SparkAutoCreate1 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
ERROR    az_command_data_logger:azlogging.py:213 (SparkJobDefinitionNotFound) The SparkJobDefinition SparkAutoCreate1 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)
Code: SparkJobDefinitionNotFound
Message: The SparkJobDefinition SparkAutoCreate1 was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=synapse-cli000001 workspace=clitest000003)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_spark_pool</td>
          <td class="col-duration">2.98</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:185 spark_log_folder is not a known attribute of class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.BigDataPoolResourceInfo&#x27;&gt; and will be ignored
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The Resource &#x27;Microsoft.Synapse/workspaces/clitest000004/bigDataPools/testpool000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource &#x27;Microsoft.Synapse/workspaces/clitest000004/bigDataPools/testpool000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The Resource &#x27;Microsoft.Synapse/workspaces/clitest000004/bigDataPools/testpool000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource &#x27;Microsoft.Synapse/workspaces/clitest000004/bigDataPools/testpool000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_spark_session_and_statements</td>
          <td class="col-duration">1.63</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  msrest.serialization:serialization.py:185 conf is not a known attribute of class &lt;class &#x27;azure.synapse.spark.models._models_py3.SparkSessionOptions&#x27;&gt; and will be ignored<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_aad_admin</td>
          <td class="col-duration">2.57</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute id will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.WorkspaceAadAdminInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (NotFound) Server administrator with name &#x27;activeDirectory&#x27; does not exist. To continue, specify a valid server administrator name or add a new server administrator.
Code: NotFound
Message: Server administrator with name &#x27;activeDirectory&#x27; does not exist. To continue, specify a valid server administrator name or add a new server administrator.
ERROR    az_command_data_logger:azlogging.py:213 (NotFound) Server administrator with name &#x27;activeDirectory&#x27; does not exist. To continue, specify a valid server administrator name or add a new server administrator.
Code: NotFound
Message: Server administrator with name &#x27;activeDirectory&#x27; does not exist. To continue, specify a valid server administrator name or add a new server administrator.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool</td>
          <td class="col-duration">5.61</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 Operation returned an invalid status &#x27;Not Found&#x27;
ERROR    az_command_data_logger:azlogging.py:213 Operation returned an invalid status &#x27;Not Found&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool_audit_policy_logentry_eventhub</td>
          <td class="col-duration">6.81</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool_classification_and_recommendation</td>
          <td class="col-duration">1.13</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool_restore_and_list_deleted</td>
          <td class="col-duration">1.94</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  msrest.serialization:serialization.py:1115 Datetime with no tzinfo will be considered UTC.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool_tde</td>
          <td class="col-duration">2.33</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_pool_threat_policy</td>
          <td class="col-duration">1.86</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sql_ws_audit_policy_logentry_eventhub</td>
          <td class="col-duration">3.72</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_sqlscript</td>
          <td class="col-duration">3.09</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>test_sqlscript1export success
<br/> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 Operation returned an invalid status &#x27;Not Found&#x27;
ERROR    az_command_data_logger:azlogging.py:213 Operation returned an invalid status &#x27;Not Found&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_trigger</td>
          <td class="col-duration">1.31</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (TriggerNotFound) The Trigger trigger was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
Code: TriggerNotFound
Message: The Trigger trigger was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
ERROR    az_command_data_logger:azlogging.py:213 (TriggerNotFound) The Trigger trigger was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)
Code: TriggerNotFound
Message: The Trigger trigger was not found in (subscription=051ddeca-1ed6-4d8b-ba6f-1ff561e5f3b3 resourceGroup=zzy-test-rg workspace=testsynapseworkspace)<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_workspace_package</td>
          <td class="col-duration">2.05</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:187 Readonly attribute name will be ignored in class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.IpFirewallRuleInfo&#x27;&gt;
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (LibraryDoesNotExistInWorkspace) The LibraryArtifact wordcount.jar does not exist.
Code: LibraryDoesNotExistInWorkspace
Message: The LibraryArtifact wordcount.jar does not exist.
ERROR    az_command_data_logger:azlogging.py:213 (LibraryDoesNotExistInWorkspace) The LibraryArtifact wordcount.jar does not exist.
Code: LibraryDoesNotExistInWorkspace
Message: The LibraryArtifact wordcount.jar does not exist.<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_workspaces</td>
          <td class="col-duration">2.41</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group &#x27;synapse&#x27; is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  cli.azure.cli.command_modules.synapse.manual._validators:_validators.py:62 Parameter --repository-type is missing, the following arguments are ignored: --host-name ,--account-name ,--collaboration-branch ,--repository-name ,--root-folder--project-name ,--tenant-id. Repository configuration will not work.
WARNING  msrest.serialization:serialization.py:185 sql_admin_login_password is not a known attribute of class &lt;class &#x27;azure.mgmt.synapse.models._models_py3.WorkspacePatchInfo&#x27;&gt; and will be ignored
ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 (ResourceNotFound) The Resource &#x27;Microsoft.Synapse/workspaces/clitest000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource &#x27;Microsoft.Synapse/workspaces/clitest000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
ERROR    az_command_data_logger:azlogging.py:213 (ResourceNotFound) The Resource &#x27;Microsoft.Synapse/workspaces/clitest000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource &#x27;Microsoft.Synapse/workspaces/clitest000003&#x27; under resource group &#x27;synapse-cli000001&#x27; was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix<br/></div></td></tr></tbody></table></body></html>